version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8080:80'
    environment:
      - VITE_BASE_URL=https://norma.nomoreparties.space/api/
