version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8081:5173'
    volumes:
      - ./src:/app/src:ro
      - ./index.html:/app/index.html
    env_file:
      - .env
