version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8081:5173'
    volumes:
      - ./src:/app/src:ro
    environment:
      - VITE_BASE_URL=https://norma.nomoreparties.space/api/
